
title: Abizer's Portfolio
subtitle: This is who I am and what I do ;)
description: >- # this means to ignore newlines until "baseurl:"
  Hello! I'm Abizer nice to meet you!
author: Abizer Naseem
email: tigerabizer@gmail.com
avatar: assets/images/avatar.jpg

linkedin_url: https://www.linkedin.com/in/abizer-naseem-5a267a18b/
github_url: https://github.com/Ab1z3rNaseem
stackoverflow_url: https://drive.google.com/file/d/1nSy3kryZoKd7NdTmRco8FsS2AoGaicYW/view?usp=sharing


# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: Ab1z3r/Portfolio
collections: [sections]
